name: Go

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**/*.go'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache: true
      - name: Run tests
        run: go test ./... -coverprofile=coverage.out -covermode=count
      - name: Run octocov
        if: runner.os == 'Linux'
        uses: k1LoW/octocov-action@a167dc0dee441b7ffc45e1b862ab55ec0d87f278 # v1.5.2
      - name: Extract coverage
        if: runner.os == 'Linux' && github.ref == 'refs/heads/main'
        run: |
          COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
      - name: Update coverage badge
        if: runner.os == 'Linux' && github.ref == 'refs/heads/main'
        uses: Schneegans/dynamic-badges-action@28b0fa8bdeb46170ac397105ece0c1fe58f68910 # v1.9.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 5f07873547f89c2d2b930848a96e9113
          filename: enter-coverage.json
          label: coverage
          message: ${{ env.COVERAGE }}%
          valColorRange: ${{ env.COVERAGE }}
          minColorRange: 0
          maxColorRange: 100
